# Copyright (c) 2024 - now Shuaiwen Cui
# Built upon MkDocs & Material for MkDocs

# Project information
site_name: NexNode
site_url: https://localhost:8000/ # build and run on server, to visit it, type in the server's IP address and port number like this: xxx.xxx.xxx.xxx:8000
site_author: Shuaiwen Cui
site_description: >-
  
# Repository
repo_name: Shuaiwen-Cui/NexNode
repo_url: https://github.com/Shuaiwen-Cui/NexNode.git

# Copyright
copyright: Copyright &copy; 2025 ~ now | 🚀 Shuaiwen Cui (Shaun)

# Configuration
theme:
  name: material
  language: en
  logo: static/images/mainboard.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand # expand the side navigation bar by default
    - navigation.footer
    - navigation.indexes # documents can be directly attached to sections, which is particularly useful for providing overview pages
    # - navigation.instant
    - navigation.instant.prefetch # for large file
    - navigation.instant.progress # loading progress bar
    - navigation.path # breadcrumb path on top of page
    # - navigation.prune # only build the visible part of the navigation tree
    - navigation.sections # navigation - top level will render as sections
    - navigation.tabs
    - navigation.tabs.sticky # tabs stick to the top of the page
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate # toc is merged into the left navigation bar
  palette:
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: static/images/logo.png
  icon:
    logo: logo
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag
      hardware-tag: fontawesome/solid/microchip
      software-tag: fontawesome/solid/laptop-code

# Plugins
plugins:
  - tags
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  # - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  # - privacy
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          # site_name: Infinity
        - locale: zh
          name: 简体中文
          build: true
          nav_translations: # note that all titles and subtitles in the navigation bar that need to be translated can be put here, but with no indentation
            ABOUT: 关于
            ROADMAP: 路线图
            HARDWARE-ESP: 硬件-ESP32
            SYSTEM: 系统设计
            COMPONENTS: 元器件选择
            SCHEMATIC: 原理图
            LAYOUT: PCB布局
            KICK-START: 快速上手
            SOFTWARE-ESP: 软件-ESP32
            INITIALIZATION: 初始化
            IOT-CORE: 物联网节点-核心
            IOT-MORE: 物联网节点-扩展
            ESP32: ESP32
            HARDWARE: 硬件
            ENVIRONMENT: 环境
            HANDS-ON: 实践
            TEMPLATE: 模板
            CORE: 核心功能
            CORE DEV: 核心功能-开发
            MODULE LIST: 核心功能-模块列表
            CORE-CONTROL: 核心功能-控制
            CORE-COMMUNICATION: 核心功能-通信
            CORE-PERCEPTION: 核心功能-感知
            CORE-ACTUATION: 核心功能-执行
            NOTE: 笔记
            CODE: 代码
            INTEGRATION: 集成
            LED: LED灯
            EXIT: 外部中断
            TIMER: 定时器
            RTC: 实时时钟
            RNG: 随机数生成器
            SPI: 串行外设接口SPI
            LCD: 液晶显示屏
            SD-CARD: SD卡
            MORE: 外围功能
            MORE-PERCEPTION: 扩展功能-感知
            DHT11: 数字温湿度传感器-DHT11
            ADXL355: 三轴加速度传感器-ADXL355
            DS3231: 实时时钟模块-DS3231
            STM32: STM32
            DNESP32S3M: DNESP32S3M
            PROJECT-CONSTRUCTION: 项目构建
            MAIN-CONTROL: 主控
            I2C: 内部集成电路总线I2C
            # TF-CARD: TF(SD)卡
            # FILE-SYSTEM: 文件系统(SPIFFS)
            PERCEPTION: 感知
            IMU-MPU6050: 惯性测量单元-MPU6050
            COMMUNICATION: 通信
            WIFI: WIFI
            MQTT: MQTT
            ACTUATION: 执行
            MIDDLEWARE: 中间件
            ESP-DSP: ESP-DSP 数字信号处理
            ESP-DL: ESP-DL 深度学习
            DNESP32S3: DNESP32S3
            FKH743M2-IIT6: FKH743M2-IIT6
            RELEASE: 发布

# # Hooks
# hooks:
#   - material/overrides/hooks/shortcodes.py
#   - material/overrides/hooks/translations.py 

# Additional configuration 
extra:
  generator: false
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    # property: GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Chinese
  #     link: /zh/
  #     lang: zh
  social:
    - icon: fontawesome/solid/house
      link: http://www.cuishuaiwen.com/
    - icon: fontawesome/brands/github
      link: https://github.com/Shuaiwen-Cui
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shaun-shuaiwen-cui/
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Shuaiwen-Cui
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0003-4447-6687
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ShuaiwenC
  tags:
    Default: default-tag
    Hardware: hardware-tag
    Software: software-tag
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.

# Extra Configuration 
extra_javascript:
  # - https://giscus.app/client.js
  # - javascripts/katex.js 
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - javascripts/embed-pdf.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page Navigation Tree
nav:
  - ABOUT: 
      - "index.md"
  - ROADMAP:
      - "ROADMAP/roadmap.md"
  - HARDWARE-ESP:
      - SYSTEM:
          - "HARDWARE-ESP/SYSTEM/system.md"
      - COMPONENTS:
          - "HARDWARE-ESP/COMPONENTS/components.md"
      - SCHEMATIC:
          - "HARDWARE-ESP/SCHEMATIC/schematic.md"
      - LAYOUT:
          - "HARDWARE-ESP/LAYOUT/layout.md"
  - SOFTWARE-ESP:
      - KICK-START:
          - HARDWARE: "./SOFTWARE-ESP/KICK_START/HARDWARE/hardware.md"
          - ENVIRONMENT: "./SOFTWARE-ESP/KICK_START/ENVIRONMENT/environment.md"
          - HANDS-ON: "./SOFTWARE-ESP/KICK_START/HANDS-ON/hands-on.md"
          - TEMPLATE: "./SOFTWARE-ESP/KICK_START/TEMPLATE/template.md"
      - INITIALZATION:
          - INITIALIZATION: "SOFTWARE-ESP/INITIALZATION/initialization.md"
          - ROADMAP: "SOFTWARE-ESP/INITIALZATION/roadmap.md"
      - CORE:
          - CORE DEV: "SOFTWARE-ESP/CORE/core.md"
          - MODULE LIST: "SOFTWARE-ESP/CORE/list.md"
      - CORE-CONTROL:
          # - "SOFTWARE-ESP/CORE-CONTROL/core-control.md"
          - EXIT:
              - NOTE: "SOFTWARE-ESP/CORE-CONTROL/EXIT/note.md"
              - CODE: "SOFTWARE-ESP/CORE-CONTROL/EXIT/code.md"
              - INTEGRATION: "SOFTWARE-ESP/CORE-CONTROL/EXIT/integration.md"
          - TIMER:
              - NOTE: "SOFTWARE-ESP/CORE-CONTROL/TIMER/note.md"
              - CODE: "SOFTWARE-ESP/CORE-CONTROL/TIMER/code.md"
              - INTEGRATION: "SOFTWARE-ESP/CORE-CONTROL/TIMER/integration.md"
          - RTC:
              - NOTE: "SOFTWARE-ESP/CORE-CONTROL/RTC/note.md"
              - CODE: "SOFTWARE-ESP/CORE-CONTROL/RTC/code.md"
              - INTEGRATION: "SOFTWARE-ESP/CORE-CONTROL/RTC/integration.md"
          - RNG:
              - NOTE: "SOFTWARE-ESP/CORE-CONTROL/RNG/note.md"
              - CODE: "SOFTWARE-ESP/CORE-CONTROL/RNG/code.md"
              - INTEGRATION: "SOFTWARE-ESP/CORE-CONTROL/RNG/integration.md"
          - I2C:
              - NOTE: "SOFTWARE-ESP/CORE-CONTROL/I2C/note.md"
              - CODE: "SOFTWARE-ESP/CORE-CONTROL/I2C/code.md"
              - INTEGRATION: "SOFTWARE-ESP/CORE-CONTROL/I2C/integration.md"
          - SPI:
              - NOTE: "SOFTWARE-ESP/CORE-CONTROL/SPI/note.md"
              - CODE: "SOFTWARE-ESP/CORE-CONTROL/SPI/code.md"
              - INTEGRATION: "SOFTWARE-ESP/CORE-CONTROL/SPI/integration.md"
      - CORE-COMMUNICATION:
          - WIFI:
              - NOTE: "SOFTWARE-ESP/CORE-COMMUNICATION/WIFI/note.md"
              - CODE: "SOFTWARE-ESP/CORE-COMMUNICATION/WIFI/code.md"
              - INTEGRATION: "SOFTWARE-ESP/CORE-COMMUNICATION/WIFI/integration.md"
          - MQTT:
              - NOTE: "SOFTWARE-ESP/CORE-COMMUNICATION/MQTT/note.md"
              - CODE: "SOFTWARE-ESP/CORE-COMMUNICATION/MQTT/code.md"
              - INTEGRATION: "SOFTWARE-ESP/CORE-COMMUNICATION/MQTT/integration.md"
      # - CORE-PERCEPTION:
      #     - "SOFTWARE-ESP/CORE-PERCEPTION/core-perception.md"
      - CORE-ACTUATION:
          # - "SOFTWARE-ESP/CORE-ACTUATION/core-actuation.md"
          - LED: 
              - NOTE: "SOFTWARE-ESP/CORE-ACTUATION/LED/note.md"
              - CODE: "SOFTWARE-ESP/CORE-ACTUATION/LED/code.md"
              - INTEGRATION: "SOFTWARE-ESP/CORE-ACTUATION/LED/integration.md"
          - LCD:
              - NOTE: "SOFTWARE-ESP/CORE-ACTUATION/LCD/note.md"
              - CODE: "SOFTWARE-ESP/CORE-ACTUATION/LCD/code.md"
              - INTEGRATION: "SOFTWARE-ESP/CORE-ACTUATION/LCD/integration.md"
          - SD-CARD:
              - NOTE: "SOFTWARE-ESP/CORE-ACTUATION/SD-CARD/note.md"
              - CODE: "SOFTWARE-ESP/CORE-ACTUATION/SD-CARD/code.md"
              - INTEGRATION: "SOFTWARE-ESP/CORE-ACTUATION/SD-CARD/integration.md"
      - MORE:
          - "SOFTWARE-ESP/MORE/more.md"
      - MORE-CONTROL:
          - DS3231:
              - NOTE: "SOFTWARE-ESP/MORE-CONTROL/DS3231/note.md"
              - CODE: "SOFTWARE-ESP/MORE-CONTROL/DS3231/code.md"
              - INTEGRATION: "SOFTWARE-ESP/MORE-CONTROL/DS3231/integration.md"
      - MORE-PERCEPTION:
          - DHT11:
              - NOTE: "SOFTWARE-ESP/MORE-PERCEPTION/DHT11/note.md" 
              - CODE: "SOFTWARE-ESP/MORE-PERCEPTION/DHT11/code.md"
              - INTEGRATION: "SOFTWARE-ESP/MORE-PERCEPTION/DHT11/integration.md"
          - ADXL355:
              - NOTE: "SOFTWARE-ESP/MORE-PERCEPTION/ADXL355/note.md"
              - CODE: "SOFTWARE-ESP/MORE-PERCEPTION/ADXL355/code.md"
              - INTEGRATION: "SOFTWARE-ESP/MORE-PERCEPTION/ADXL355/integration.md"


  - RELEASE:
      - "RELEASE/v1.md"
  # - KICK-START:
  #     - ESP32:
  #         - HARDWARE: "./KICK_START/ESP32/HARDWARE/hardware.md"
  #         - ENVIRONMENT: "./KICK_START/ESP32/ENVIRONMENT/environment.md"
  #         - HANDS-ON: "./KICK_START/ESP32/HANDS-ON/hands-on.md"
  #         - TEMPLATE: "./KICK_START/ESP32/TEMPLATE/template.md"
  #     - STM32:
  #         - "KICK_START/STM32/stm32.md"
  # - DNESP32S3M:
  #     - ROADMAP: "DNESP32S3M/dnesp32s3m.md"
  #     - PROJECT-CONSTRUCTION: "DNESP32S3M/PROJECT/project.md"
  #     - MAIN-CONTROL: 
  #         - EXIT:
  #             - NOTE: "DNESP32S3M/ACTUATION/KEY(EXIT)/note.md"
  #             - CODE: "DNESP32S3M/ACTUATION/KEY(EXIT)/code.md"
  #             - INTEGRATION: "DNESP32S3M/ACTUATION/KEY(EXIT)/integration.md"
  #         - TIMER: 
  #             - NOTE: "DNESP32S3M/MAIN-CONTROL/TIMER/note.md"
  #             - CODE: "DNESP32S3M/MAIN-CONTROL/TIMER/code.md"
  #             - INTEGRATION: "DNESP32S3M/MAIN-CONTROL/TIMER/integration.md"
  #         - RTC:
  #             - NOTE: "DNESP32S3M/MAIN-CONTROL/RTC/note.md"
  #             - CODE: "DNESP32S3M/MAIN-CONTROL/RTC/code.md"
  #             - INTEGRATION: "DNESP32S3M/MAIN-CONTROL/RTC/integration.md"
  #         - RNG:
  #             - NOTE: "DNESP32S3M/MAIN-CONTROL/RNG/note.md"
  #             - CODE: "DNESP32S3M/MAIN-CONTROL/RNG/code.md"
  #             - INTEGRATION: "DNESP32S3M/MAIN-CONTROL/RNG/integration.md"
  #         - SPI:
  #             - NOTE: "DNESP32S3M/MAIN-CONTROL/SPI/note.md"
  #             - CODE: "DNESP32S3M/MAIN-CONTROL/SPI/code.md"
  #             - INTEGRATION: "DNESP32S3M/MAIN-CONTROL/SPI/integration.md"
  #         - I2C:
  #             - NOTE: "DNESP32S3M/MAIN-CONTROL/I2C/note.md"
  #             - CODE: "DNESP32S3M/MAIN-CONTROL/I2C/code.md"
  #             - INTEGRATION: "DNESP32S3M/MAIN-CONTROL/I2C/integration.md"
  #         - SD-CARD:
  #             - NOTE: "DNESP32S3M/MAIN-CONTROL/SD-CARD/note.md"
  #             - CODE: "DNESP32S3M/MAIN-CONTROL/SD-CARD/code.md"
  #             - INTEGRATION: "DNESP32S3M/MAIN-CONTROL/SD-CARD/integration.md"
  #         # - TF-CARD:
  #         #     - NOTE: "DNESP32S3M/MAIN-CONTROL/TF-CARD/note.md"
  #         #     - CODE: "DNESP32S3M/MAIN-CONTROL/TF-CARD/code.md"
  #         #     - INTEGRATION: "DNESP32S3M/MAIN-CONTROL/TF-CARD/integration.md"
  #         # - FILE-SYSTEM:
  #         #     - NOTE: "DNESP32S3M/MAIN-CONTROL/FILE-SYSTEM/note.md"
  #         #     - CODE: "DNESP32S3M/MAIN-CONTROL/FILE-SYSTEM/code.md"
  #         #     - INTEGRATION: "DNESP32S3M/MAIN-CONTROL/FILE-SYSTEM/integration.md"
  #     - PERCEPTION: 
  #         - IMU-MPU6050:
  #             - NOTE: "DNESP32S3M/PERCEPTION/IMU-MPU6050/note.md"
  #             - CODE: "DNESP32S3M/PERCEPTION/IMU-MPU6050/code.md"
  #             - INTEGRATION: "DNESP32S3M/PERCEPTION/IMU-MPU6050/integration.md"
  #     - COMMUNICATION: 
  #         - WIFI: 
  #             - NOTE: "DNESP32S3M/COMMUNICATION/WIFI/note.md"
  #             - CODE: "DNESP32S3M/COMMUNICATION/WIFI/code.md"
  #             - INTEGRATION: "DNESP32S3M/COMMUNICATION/WIFI/integration.md"
  #         - MQTT:
  #             - NOTE: "DNESP32S3M/COMMUNICATION/MQTT/note.md"
  #             - CODE: "DNESP32S3M/COMMUNICATION/MQTT/code.md"
  #             - INTEGRATION: "DNESP32S3M/COMMUNICATION/MQTT/integration.md"
  #     - ACTUATION: 
  #         - LED: 
  #             - NOTE: "DNESP32S3M/ACTUATION/LED/note.md"
  #             - CODE: "DNESP32S3M/ACTUATION/LED/code.md"
  #             - INTEGRATION: "DNESP32S3M/ACTUATION/LED/integration.md"
  #         - LCD:
  #             - NOTE: "DNESP32S3M/ACTUATION/LCD/note.md"
  #             - CODE: "DNESP32S3M/ACTUATION/LCD/code.md"
  #             - INTEGRATION: "DNESP32S3M/ACTUATION/LCD/integration.md"
  #     - MIDDLEWARE: 
  #         # - MIDDLEWARE: "DNESP32S3M/MIDDLEWARE/middleware.md"
  #         - ESP-DSP: "DNESP32S3M/MIDDLEWARE/ESP-DSP/esp-dsp.md"
  #         - ESP-DL: "DNESP32S3M/MIDDLEWARE/ESP-DL/esp-dl.md"
  # - DNESP32S3:
  #     - ROADMAP: "DNESP32S3/dnesp32s3.md"
  # - FKH743M2-IIT6:
  #     - ROADMAP: "FKH743M2-IIT6/fkh743m2-iit6.md"


# if there are sub nodes under a node, then there should not be a link right after the node. All the stuff should be placed under the node.

# example

# [incorrect use]
# - CLOUD: "./CLOUD/cloud.md"
#     - CLOUD-TECH: "./CLOUD/CLOUD-TECH/cloud-tech.md"

# [correct use]
# - CLOUD: 
#     - "./CLOUD/cloud.md"
#     - CLOUD-TECH: "./CLOUD/CLOUD-TECH/cloud-tech.md"